version: '3.7'
services:

  osticket-app:
    image: campbellsoftwaresolutions/osticket
    container_name: osticket-app
    environment:
      - MYSQL_HOST=osticket-db
      - MYSQL_PASSWORD=verysecret1234
      - MYSQL_USER=osticket
      - INSTALL_NAME=M437 My Helpdesk
    networks:
      - services
    restart: always
    ports:
      - 8080:80

  osticket-db:
    image: mariadb:10.5-focal
    container_name: osticket-db
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=securepassword
      - MYSQL_DATABASE=osticket
      - MYSQL_USER=osticket
      - MYSQL_PASSWORD=verysecret1234
    networks:
      - services
    restart: always

networks:
  proxy:
    external: true
  services:
    external: true
